databases:
  - name: dpg-d1m1hiripnbc73finsu0-a

services:
  - type: web
    name: bdi-gb-zoo-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python init_db.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL
        fromDatabase:
          name: dpg-d1m1hiripnbc73finsu0-a
          property: internalUrl